### ISSUE TITLE
Shift key doesn't switch dictionaries anymore

### ISSUE THREAD

**Issue by Ginko-sensei** [birchill/10ten-ja-reader#659] opened 2021-07-02 18:56 UTC
When I press the `shift` key, Rikaichamp doesn't switch dictionaries anymore. I checked and it's still turned on in the settings.
`Enter` key still works but it's a lot less convenient than `shift`.
I tried disabling and re-enabling `shift` in the settings but it still doesn't work.

I'm using Firefox 89.0.2 (64-bit) and Rikaichamp 0.5.12.

**Comment by birtles** [comment] 2021-07-02 23:35
Oh I'm really sorry to hear that. It still works for me so I wonder what the problem is.

Do you hold down a key like <kbd>Ctrl</kbd> in order to display the pop-up? I noticed in #658 that we ignore <kbd>Shift</kbd> when another modifier (like <kbd>Ctrl</kbd>) is being pressed, but we allow <kbd>Enter</kbd>. In that case you need to release <kbd>Ctrl</kbd> then press <kbd>Shift</kbd>. (But in #658 I might try to change that so I'd like to know if this was the problem.)

The only behavior that has changed recently that I can think of is that I dropped the function where you can hold <kbd>Shift</kbd> while moving the mouse to force it to only show the kanji dictionary. I've re-added that feature now and it will be available again from the next release.

**Comment by Ginko-sensei** [comment] 2021-07-03 07:58
No, I'm not using `Ctrl`, I didn't even realize what it did until today.
However, after investigating some more, I found the reason. It's because I activated the `privacy.resistFingerprinting` setting in `about:config`. As soon as I deactivate it, it works again.

Apparently, it's already known that this option breaks some shortcuts in Firefox (see [this open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1470828)). I don't know if there's a way for you to work around it but I guess it wouldn't be a priority at all.

Otherwise, I'll just learn to live with using `Enter` to switch dictionaries (even though I'd still like to assign this to another key on the left of the keyboard, not necessarily `Shift`).

**Comment by birtles** [comment] 2021-07-05 02:07
> However, after investigating some more, I found the reason. It's because I activated the `privacy.resistFingerprinting` setting in `about:config`. As soon as I deactivate it, it works again.

Great, thanks for investigating that!

> Apparently, it's already known that this option breaks some shortcuts in Firefox (see [this open bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1470828)). I don't know if there's a way for you to work around it but I guess it wouldn't be a priority at all.

Yes, it doesn't seem like there's much we can do to fix it except perhaps to add a warning to the options page -- but we'd only want to display that when `privacy.resistFingerprinting` and I'm not sure if that's able to be detected reliably.

> Otherwise, I'll just learn to live with using `Enter` to switch dictionaries (even though I'd still like to assign this to another key on the left of the keyboard, not necessarily `Shift`).

That seems like a very reasonable request. What other key would be suitable?

Unfortunately the keys have fairly complex interaction so it's not particularly easy to add other options, but we can certainly try.

**Comment by Ginko-sensei** [comment] 2021-07-05 15:56
> That seems like a very reasonable request. What other key would be suitable?

Good question. Keyboard modifiers are ideal for this but since we can't use them in this case...
Maybe the one above `Tab` and left of `1`? This key doesn't always do the same thing across different keyboard layouts but at least, it seems to always exist so maybe it can be used?

**Comment by birtles** [comment] 2021-07-06 00:45
> Maybe the one above `Tab` and left of `1`? This key doesn't always do the same thing across different keyboard layouts but at least, it seems to always exist so maybe it can be used?

That's a really interesting idea. Normally we use the `key` attribute of `KeyboardEvents` which changes depending on the keyboard layout. If we use the `code` attribute, however, we can target that key.

For example, on my (Japanese) keyboard, if I run:

```js
window.addEventListener('keydown', event => { console.log(event.code, event.key) })
```

in the console, then focus the web page and press the key you describe, I get:

```
Backquote Zenkaku
```

So we could target `Backquote` and that would work. The hard part is probably deciding what to show in the options page. How do we describe that key to the user because for some users it will be the ` key, but for other users it will be the key to switch between hiragana / romaji.

**Comment by birtles** [comment] 2021-07-06 00:59
> The hard part is probably deciding what to show in the options page. How do we describe that key to the user because for some users it will be the ` key, but for other users it will be the key to switch between hiragana / romaji.

It looks like there is an API for this but it's only in Chrome/Edge: [`getLayoutMap()`](https://developer.mozilla.org/en-US/docs/Web/API/Keyboard/getLayoutMap)

It exposes a pretty significant fingerprinting surface though so Safari/Firefox are unlikely to implement it, e.g. see https://github.com/WICG/keyboard-map/issues/30, https://github.com/brave/brave-browser/issues/2655 etc.

**Comment by Ginko-sensei** [comment] 2021-07-06 06:49
I tried executing your `addEventListener` code in my browser, using my French keyboard (yet another specific layout) and I think this `resistFingerprinting` (RFP) option is still going to be a problem...

For the key above `Tab`, the result is `<empty string> ²` with RFP on and it's `Backquote ²` with RFP off.
Incidentally, pushing the `Shift` key displays ` ShiftLeft Shift` when RFP is off but absolutely nothing happens when RFP is on so that may explain why it doesn't work for me.

The weird thing is, the `Ctrl` key behaves in the same way: `ControlLeft Control` when RFP is off, nothing happening when RFP is on. And yet, I'm still able to use this key to display the Rikaichamp popup if I configured it in the settings.
Is there any difference in how you handle the `Ctrl` and `Shift` keys? Since the first one seems to work even with RFP on but not the second one.

**Comment by birtles** [comment] 2021-07-06 08:05
> I tried executing your `addEventListener` code in my browser, using my French keyboard (yet another specific layout) and I think this `resistFingerprinting` option (RFP) is still going to be a problem...

Thank you for trying that out! That saves a lot of time knowing that this approach won't fix the issue after all.

> The weird thing is, the `Ctrl` key behaves the same way: `ControlLeft Control` when RFP is off, nothing happening when RFP is on. And yet, I'm still able to use this key to display the Rikaichamp popup if I configured it in the settings.

I'm not sure, but I think RFP may suppress modifiers from `KeyboardEvents` but not from `MouseEvents` (since the latter wouldn't leak information about your keyboard layout) so we can still detect that `Ctrl` is being pressed when a mouse event occurs.

It sounds like our best option is to choose a regular character like <kbd>s</kbd> ("switch"?) or something.

**Comment by Ginko-sensei** [comment] 2021-07-06 11:27
> It sounds like our best option is to choose a regular character like s ("switch"?) or something.

It might be the best choice, even though `s` is kinda lost among other keys.

The only other keys I can think of are `Tab` and `Esc` which both seem to behave normally, even with RFP on.
But `Tab` already changes the focus in the page (but maybe this behaviour can be blocked while Rickaichamp popup is displayed) and I'm not sure if using `Esc` to switch dictionaries is a good idea (if it's even possible)...

**Comment by birtles** [comment] 2021-07-07 02:00
> The only other keys I can think of are `Tab` and `Esc` which both seem to behave normally, even with RFP on.
> But `Tab` already changes the focus in the page (but maybe this behaviour can be blocked while Rickaichamp popup is displayed) and I'm not sure if using `Esc` to switch dictionaries is a good idea (if it's even possible)...

Yes <kbd>Tab</kbd> seems very attractive but I think it could be frustrating because it means that if the popup shows up, even accidentally, you'd be unable to use the keyboard to navigate the page.

For <kbd>Esc</kbd>, if we make Rikaichamp listed to the <kbd>Esc</kbd> key, I think it should probably close the popup.

I don't suppose you happen to have a "Media Track Next" button on your keyboard? That would be easy to add support for. Or perhaps the <kbd>Pause</kbd> key? I have one of those in the top-right of my keyboard and it looks like we could probably use that.

Failing that, I guess it would be <kbd>s</kbd> or perhaps <kbd>n</kbd> (for "next").

**Comment by SaltfishAmi** [comment] 2021-07-07 04:26
> I don't suppose you happen to have a "Media Track Next" button on your keyboard? That would be easy to add support for. Or perhaps the Pause key? I have one of those in the top-right of my keyboard and it looks like we could probably use that.

I suggest a regular character key. Because there're many limited keyboard layouts (like those on laptops and tablets) and nobody could tell what functional keys are missing, but the character keys are always there.
...or, are they?

**Comment by birtles** [comment] 2021-07-07 04:28
> I suggest a regular character key. Because there're many limited keyboard layouts (like those on laptops and tablets) and nobody could tell what functional keys are missing, but the character keys are always there.

Right, I agree. I don't have a "Media Track Next" on any of my keyboards. I'm just looking for a solution for the small set of users who have RFP enabled and don't want to use <kbd>Enter</kbd>.

I wonder how commonly available <kbd>Pause</kbd> is.

**Comment by SaltfishAmi** [comment] 2021-07-07 05:27
> I wonder how commonly available Pause is.

Well, my old 14" laptop doesn't have it and neither does my Surface Pro Type Cover.
Regular desktop keyboards often have them (especially the cheap ones), but I'm not familiar with those higher-end mechanic gaming keyboards (many of them does not have numpad afaik)

**Comment by birtles** [comment] 2021-07-07 05:32
> Well, my old 14" laptop doesn't have it and neither does my Surface Pro Type Cover.
> Regular desktop keyboards often have them (especially the cheap ones), but I'm not familiar with those higher-end mechanic gaming keyboards (many of them does not have numpad afaik)

Thanks! That's good to know. I think the "Happy Hacker" (HHKB) series don't normally have it although I got a [HHKB/Realforce collaboration model](https://www.pfu.fujitsu.com/rfkeyboard/) that does. I guess <kbd>n</kbd> or somesuch is our safest bet.

**Comment by Ginko-sensei** [comment] 2021-07-07 06:53
> For Esc, if we make Rikaichamp listed to the Esc key, I think it should probably close the popup.

Yeah, that would make a lot more sense than it switching dictionaries. I was actually surprised it didn't already do that when I tried yesterday 😃
> I don't suppose you happen to have a "Media Track Next" button on your keyboard? That would be easy to add support for. Or perhaps the Pause key? I have one of those in the top-right of my keyboard and it looks like we could probably use that.

I don't have such media keys no. There is a `Pause` key (I think this one is semi-standard, like `Print Screen` and such) but it's even farther to the right than `Enter` so it would be even less convenient in my case.
> Failing that, I guess it would be s or perhaps n (for "next").

In the end, it really seems like our best option. Personally, I would go with `s` because it's located in the left part of the keyboard.

**Comment by birtles** [comment] 2021-07-08 04:21
> > Failing that, I guess it would be s or perhaps n (for "next").
> 
> In the end, it really seems like our best option. Personally, I would go with `s` because it's located in the left part of the keyboard.

I'd actually like to keep <kbd>s</kbd> unused for now. The reason is I'd like to introduce a "sticky" mode at some point. Some users have asked for things like being able to scroll the pop-up when there are more definitions than we can show. I had in mind that you could press something like <kbd>s</kbd> and make the popup sticky so that it doesn't disappear when you move your mouse.

How inconvenient would <kbd>n</kbd> be?

Unfortunately <kbd>d</kbd> is already used for toggling definitions (off by default).

**Comment by birtles** [comment] 2021-07-08 04:22
(For what it's worth, I went to implement this today and it's literally a one-line change.)

**Comment by Ginko-sensei** [comment] 2021-07-08 06:37
> How inconvenient would n be?

Well, not that inconvenient, it would still be better than `Enter`. And that sticky mode would be useful sometimes.

Now that I think about the big obvious button, there is also the `Space` key but it might be unusable for the same reason as the `Tab` key.

**Comment by birtles** [comment] 2021-07-08 07:05
> Now that I think about the big obvious button, there is also the `Space` key but it might be unusable for the same reason as the `Tab` key.

Right. I wanted to use <kbd>Space</kbd> for sticky mode but I'm afraid that for people who use <kbd>Space</kbd> to scroll, they'll scroll, the popup will show up because the mouse falls over some Japanese text and then they'll be unable to scroll anymore.

> Of course, the absolute best solution would be customizable keys but that would _probably_ be a tad more complicated than a one-line change.

Right. The shortcut key to activate the add-on is completely customizable but making the other keys more customizable would be a bit of work, partly just because we'd probably need to make sure they don't conflict with each other.

**Closed** 2021-07-08 07:09 UTC

**Comment by birtles** [comment] 2021-07-22 05:35
Just letting you know that I have finally released an updated version that includes <kbd>n</kbd> key as an option.

**Comment by Ginko-sensei** [comment] 2021-07-22 06:43
Yes, Rikaichamp (I mean, 10ten :-D) just updated this morning and it's working fine. Thanks!
