### ISSUE TITLE
Popup sizing issues

### ISSUE THREAD

**Issue by Tomalak** [birchill/10ten-ja-reader#1314] opened 2023-09-11 07:57 UTC
Sometimes a vertical scrollbar appears in the collapsed view of the popup, but goes away in the expanded view. This messes with the line break position and the last line of the entry gets pushed down into the "fade-out" area, making it harder to read. 

Example 餌やり

![image](https://github.com/birchill/10ten-ja-reader/assets/28300/2cfc4144-276c-4ab8-ae00-e6e9232e7d76)

After clicking an entry, the expanded view is resized to fit the context menu, but upon clicking "Cancel", the size does not reset.

![image](https://github.com/birchill/10ten-ja-reader/assets/28300/3b0e7496-34ab-4a89-97a0-0a559cce9359)

Also, the text highlight vanishes in this situation, but I feel it should probably be maintained?

I'm on Firefox 117 and extension version 1.15.1.

**Comment by birtles** [comment] 2023-09-11 08:33
Hi! Thanks for filing this.

> Sometimes a vertical scrollbar appears in the collapsed view of the popup, but goes away in the expanded view. This messes with the line break position and the last line of the entry gets pushed down into the "fade-out" area, making it harder to read.
> 
> Example 餌やり

Yep, that doesn't look right. What OS are you on? I can't reproduce this on Windows but it looks like you have thicker scrollbars so I guess that's why. If so, I think the solution is probably to set up a scrollbar gutter.

> After clicking an entry, the expanded view is resized to fit the context menu, but upon clicking "Cancel", the size does not reset.

That part is deliberate. If we reset the popup size after you clicked cancel, your mouse might end up outside the popup causing the popup to disappear which would be annoying. We reset the popup size if it is pinned or if you're on a touch device since you don't need to worry about the popup disappearing in those cases.

> Also, the text highlight vanishes in this situation, but I feel it should probably be maintained?

That seems like a separate bug. I'm not sure why that's happening.

**Comment by Tomalak** [comment] 2023-09-11 10:10
> What OS are you on? 

I'm on Windows 10, I didn't think that would make much of a difference. But I do have the "Automatically hide scrollbars" system setting switched off, not sure if Firefox uses that here, but it might have an influence.

> That part is deliberate.

Ah, makes sense.

> That seems like a separate bug.

Yeah, but creating two issues seemed a bit excessive. :)

**Comment by birtles** [comment] 2023-09-12 01:21
> > What OS are you on?
> 
> I'm on Windows 10, I didn't think that would make much of a difference. But I do have the "Automatically hide scrollbars" system setting switched off, not sure if Firefox uses that here, but it might have an influence.

Thanks. That seems to be it. With that setting applied _and_ tabs turned off, I can reproduce it.

> > That seems like a separate bug.
> 
> Yeah, but creating two issues seemed a bit excessive. :)

It's fine to split them out. I've filed this as #1315 for now but as I mentioned there, it might not be worth fixing this since it should be fixed once Firefox ships the Highlight API on all channels.

**Closed** 2023-09-12 07:49 UTC
