### ISSUE TITLE
Thunderbird support

### ISSUE THREAD

**Issue by FmT0** [birchill/10ten-ja-reader#46] opened 2018-07-06 05:51 UTC
Thunderbird 60 is planned to take the same addon transition as Firefox with Quantum. Sadly no Japanese addon is working at the moment.
Since rikaichamp is for me the best one at the moment for the new Firefox, I hope you can make it work in new Thunderbird as well.

**Comment by birtles** [comment] 2018-07-07 03:43
Are you saying there is a plan to support Web Extensions in Thunderbird? Do you have more information about this?

**Comment by FmT0** [comment] 2018-07-07 04:53
There is some information on this page, with a link to the official bug tracker
https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57
And information on a new release soon on
https://www.ghacks.net/2018/07/06/thunderbird-60-extension-and-theme-changes/

Hope you can do something, addon is installing fine on thunderbird 60b9 but there is no way to access options or activate. Maybe it's still work in progress and need just a few adjustement.

**Comment by birtles** [comment] 2018-07-08 22:44
I think this will be a lot easier once Thunderbird supports Web Extensions ([bug 1396172](https://bugzilla.mozilla.org/show_bug.cgi?id=1396172)). It looks like there has been fairly recent activity on [bug 1468667](https://bugzilla.mozilla.org/show_bug.cgi?id=1468667) so hopefully it's not too far off.

**Comment by birtles** [comment] 2018-11-09 11:28
Got another request for this today. Apparently Web Extensions support for Thunderbird comes in version 63. I hope I can look into this in the near-ish future.

**Comment by jmbattle0** [comment] 2018-11-13 04:57
Hello Brian,

I updated Thunderbird to 60.3.0 today and in doing so lost support for the original rikaichan extension that has served me well for so many years. ;(

This led me to investigate alternative extensions, of which rikaichamp appears to be the most actively developed.  I would therefore like to join others in requesting Thunderbird support be added to rikaichamp.

I managed to download the rikaichamp-0.0.26-fx.xpi file from the Firefox add-ons site, but while the extension appears to install into Thunderbird, there does not seem to be a way to trigger rikaichamp to startup - even after disabling the strict compatibility flag.

Before I bite the bullet and downgrade to the previous version of Thunderbird, is there any way of hacking the existing 0.0.26 version of rikaichamp to work with the latest version (however buggy)?

Thank you in advance!

**Comment by birtles** [comment] 2018-11-13 08:10
Yes, you're right. I just tried installing it too, and although it doesn't complain of any errors, it doesn't seem to add any buttons to the toolbar or be useable in any way.

I'm not sure what APIs Thunderbird supports. I guess it doesn't support the browser action API.

I don't have a lot of time to spend on this, so if anyone is able to provide pointers to, e.g. other Thunderbird Web Extensions that would be helpful.

**Comment by gunzizle** [comment] 2018-12-12 05:39
Let me also upvote the request for Thunderbird v60+ support...

**Comment by birtles** [comment] 2018-12-28 07:16
I started to dig into this a bit. Using a trunk build of Thunderbird, I tried loading the generated extension `.zip` file using Tools → Developer Tools → Debug Addons and then loading it as a temporary add-on. Looking in the Error Console I get:

```
1545980750016	addons.webextension.<unknown>	WARN	Loading extension 'null': Reading manifest: Error processing permissions.1: Value "contextMenus" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["addressBooks"], be one of ["activeTab", "tabs", "tabHide"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["pkcs11"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
1545980750056	addons.webextension.{59812185-ea92-4cca-8ab7-cfcacee81281}	WARN	Loading extension '{59812185-ea92-4cca-8ab7-cfcacee81281}': Reading manifest: Error processing permissions.1: Value "contextMenus" must either: must either [must either [be one of ["clipboardRead", "clipboardWrite", "geolocation", "idle", "notifications"], be one of ["addressBooks"], be one of ["activeTab", "tabs", "tabHide"], be one of ["browserSettings"], be one of ["cookies"], be one of ["downloads", "downloads.open"], be one of ["topSites"], be one of ["webNavigation"], or be one of ["webRequest", "webRequestBlocking"]], be one of ["alarms", "mozillaAddons", "storage", "unlimitedStorage"], be one of ["pkcs11"], be one of ["contextualIdentities"], be one of ["dns"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], be one of ["telemetry"], be one of ["theme"], or match the pattern /^experiments(\.\w+)+$/], or must either [be one of ["<all_urls>"], must either [match the pattern /^(https?|wss?|file|ftp|\*):\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$/, or match the pattern /^file:\/\/\/.*$/], or match the pattern /^resource:\/\/(\*|\*\.[^*/]+|[^*/]+)\/.*$|^about:/]
```

So clearly Thunderbird doesn't like the manifest.

After that I also get an error:

```
TypeError: tab is undefined[Learn More] rikaichamp-background.js:3614:24
```

I could really use help with this issue so if anyone has time to play around please report what you find here.

If anyone wants to try I suggest the first steps would be:

1. Download a [beta](https://www.thunderbird.net/en-US/channel/) or even [daily build](https://archive.mozilla.org/pub/thunderbird/nightly/latest-comm-central/) of Thunderbird
2. Check out this repo
3. Run `npm install`
4. Run `npm run prepack` which should generate a .zip of rikaichamp under `web-ext-artifacts/rikaichamp-0.0.27.zip` (or `0.0.28` or so).
5. Follow the steps above to install it as a temporary add-on in Thunderbird.
6. Press Ctrl+Shift+J (hopefully that works -- otherwise try Tools → Developer Tools →Error Console) and check what errors you see in the console.

Once you get that far. The next thing would be to try tweaking `manifest.json.src` to try and resolve the issues reported about the manifest. After you tweak it, you'll want to run steps 4~6 again from above. If you discover anything, please report it here.

**Comment by bacintom** [comment] 2019-03-05 05:45
_disclaimer: I actually don't know or understand anything to WebExtensions. I also happen to hate javascript._

I will share some of my findings. I couldn't get the extension to work, but I hope it can be useful.:

**1)About the manifest issue:**

[this document](https://media.readthedocs.org/pdf/thunderbird-webextensions/latest/thunderbird-webextensions.pdf) (Feb 25, 2019 version) states:
> The menus API first appeared in Thunderbird 66 (see bug 1503421). It is basically the same as the Firefox menus API,but modified to suit Thunderbird. Note that the similarcontextMenusAPI will not be added to Thunderbird.

So, I've tried removing the "contextMenus" from the manifest. I have also added "menus" but I'm not sure there is any effect. The context menu button feature does not seem to work.

**2) About "browserAction"**

Apparently it not supported before thunderbird 64. So current common versions of thunderbird (60.x) will fail due to that.

As you mention it seems like a better idea to try on beta versions. Which is why I have tried running on thunderbird 66.0b2 from then. Then it stops complaining about browserAction

**3) Next, I fall upon the same error : `TypeError: tab is undefined`**

The error seems to be caused by the `enableTab` function from src/background.ts. Deleting the function altogether with the calls to it (and npm run build/prepack, remove extension, restart, reinstall, restart again for safety) makes this error go away (but I don't know what I've disabled by doing that, maybe that just breaks the extension too)

After all that, at some point the addon preferences showed up (but I can't figure the circumstances -- it happened once, the rest of the time addon prefs don't show up)
Also, a button show up in the top right "Rikaichamp disabled". I can't enable it, neither with the button nor Alt+R.

**4)I get this error in the "Browser console":**

`chromeModifierKeyMap is undefined ext-commands.js:287
    getModifiersAttribute chrome://messenger/content/parent/ext-commands.js:287
    from self-hosted:600
    getModifiersAttribute chrome://messenger/content/parent/ext-commands.js:286
    buildKeyFromShortcut chrome://messenger/content/parent/ext-commands.js:239
    buildKey chrome://messenger/content/parent/ext-commands.js:191
    registerKeysToDocument chrome://messenger/content/parent/ext-commands.js:171
    forEach self-hosted:3954
    registerKeysToDocument chrome://messenger/content/parent/ext-commands.js:158
    registerKeys chrome://messenger/content/parent/ext-commands.js:78
    register chrome://messenger/content/parent/ext-commands.js:88
    InterpretGeneratorResume self-hosted:1255
    next self-hosted:1210`

I assume it is related to keyboard shortcuts, but couldn't find useful hints about it.

**Comment by birtles** [comment] 2019-03-07 10:08
Thank you very much for trying! That's a great help. I hope to look at this again some time and your investigation will certainly help. Perhaps someone else will have a chance before me, however.

**Comment by ferminfm** [comment] 2019-05-16 17:02
I've had enough of the same issue and want to downgrade to an even older version of Thunderbird where all my most needed addons worked perfectly, so I posted a question on ask ubuntu, in case you can answer or want to follow that.
https://askubuntu.com/questions/1143807/how-to-go-downgrade-thunderbird-to-older-version-in-18-04

**Comment by birtles** [comment] 2019-05-16 23:02
@ferminfm Thanks for your patience with this. I have set aside July to work on rikaichamp full-time and Thunderbird support is one of the items on my list (in position 3 currently). I can't promise 100% it will be done by the end of July (these things always prove more complicated than they first appear) but I really hope it will.

**Comment by SamXtusJapan** [comment] 2019-06-18 06:10
@birtles I feel bad for not being able to help out on this topic, as my software skill are close to none, but that would be awesome if you can fix this addon !

**Comment by birtles** [comment] 2019-06-18 06:15
@SamXtusJapan Not at all. This is definitely on my radar for next month. (There are a lot of things I need to fix in Rikaichamp next month so I can't guarantee it will be done by the end of the month, but if I don't make it, it will come shortly after that in early August.)

**Comment by SamXtusJapan** [comment] 2019-06-18 06:15
@ferminfm You said you want to downgrade further because of Lightning Calendar not working on v52.x neither but as I checked it's the only addon that works with v60.x.

**Comment by ferminfm** [comment] 2019-06-19 08:44
> @ferminfm You said you want to downgrade further because of Lightning Calendar not working on v52.x neither but as I checked it's the only addon that works with v60.x. Unless it works in v60.x and not in v52.x but that would be odd. Or maybe it's different with Linux, I use Win10.

Indeed in Ubuntu GNU-Linux 18.04 the lightning addon works in 60.x but not in 52.x as far as I tried, and rikaichamp is the reverse so I cannot get both working together anymore (in the same Thunderbird version). Now lighning is working in the current version so I very much appreciate if the owner can catch up with Rikaichamp!

**Comment by SamXtusJapan** [comment] 2019-06-19 08:48
Oh really ? That's weird indeed oO

**Comment by mbinnard** [comment] 2019-08-08 16:29
Any update on Thunderbird support?  Like many others, I'm stuck on TBird 52 because I need this extension.

**Comment by birtles** [comment] 2019-08-09 02:22
Thanks for the reminder. I started digging into this today. I've made a branch to start working on this: [support-tbird](https://github.com/birtles/rikaichamp/tree/support-tbird)

So far the summary is:

* We're only targeting Thunderbird beta for now. The next major Thunderbird release should happen sometime this month and adds a lot of Web Extensions APIs so it's not worth targeting the current release version (60).
* To build with this new version do:
   * Clone the repo
   * `git checkout support-tbird`
   * `npm run build:thunderbird`
   * In Thunderbird beta go to Tools → Developer Tools → Debug Addons
   * From the debugging page choose "Load Temporary Add-on..." and select the manifest.json file from the generated `dist-thunderbird` folder.
* After making changes just do `npm run build:thunderbird` then click `Reload` under Rikaichamp from the debugging tab.

So far it will at least show and icon. It will break when you try to enable Rikaichamp however. It seems like Thunderbird doesn't support `browser.tabs.sendMessage`. I'm not sure how to target the message-view / preview pane yet or if they even get content scripts injected or not. We'll need to target compose windows too.

**Comment by birtles** [comment] 2019-08-09 06:08
I sent mail to some Thunderbird folks to see if I can get any tips on this. The best I can tell so far is to look up the appropriate tab, then call [`executeScript`](https://thunderbird-webextensions.readthedocs.io/en/68/tabs.html#executescript-tabid-details) on it, and have it look up the appropriate `<browser id="messagepage">` or `<editor id="content-frame">` element and fiddle with that.

**Comment by birtles** [comment] 2019-08-09 06:14
Looks like [bug 1504475](https://bugzilla.mozilla.org/show_bug.cgi?id=1504475) would make content scripts work in email previews.

**Comment by rzvnbr** [comment] 2020-12-05 10:49
Hi! Sorry to revive this old thread, but I would like to know if you are working (or at least planning to work) on support for recent Thunderbird versions. I would really like to be able to use again this great plugin in Thunderbird, but the last supported version seems to be very old.
Alternatively, do you have any advice on how to make things work unofficially (if this is at all possible)? Thanks a lot!

**Comment by birtles** [comment] 2020-12-06 23:58
> Hi! Sorry to revive this old thread, but I would like to know if you are working (or at least planning to work) on support for recent Thunderbird versions. I would really like to be able to use again this great plugin in Thunderbird, but the last supported version seems to be very old.

Hi! Not at all. Thank you very much for your interest! It is very helpful to have comments like this since it helps me to understand what to prioritize.

Recently some new Web Extension APIs have been added to Thunderbird so I think it might be possible to make this work at least partly now. (From memory, I think it might be possible to make it work while _reading_ messages but maybe not while _composing_.)

I do plan to support Thunderbird but my current priority list looks like:

1. Make the word dictionary be automatically updated and support multiple languages (likely early January)
2. Support Chrome and Edge
3. Support Safari
4. Support Thunderbird
5. Try to support Firefox for Android

**Comment by rzvnbr** [comment] 2020-12-07 11:02
I am glad to hear that Thunderbird is still on your priority list, and I agree with it having a lower priority compared to browser support. I am looking forward to the day when I'll be able to use again this plugin for emails (I am using it quite often in Firefox now). Good luck with your ambitious development plans!

**Comment by SamXtusJapan** [comment] 2020-12-07 11:18
@birtles I am glad that you are still considering this case. Thank you very much for creating rikaichamp in the first place. Being into hardware I can't help unfortunately.
Just a remark about the priority order. I totally understand that browsers should be prioritized, but rikaichamp is still supported on Firefox and rikaikunon Chrome so there is still an option for those who need this fabulous plugin on a browser.

However I think there is no such convenient plugin anymore for any email client as far as I know, so having it on Thunderbird as it used to work in the past would help a lot for foreigners in Japan like me who work with pop3 emails in Japanese. I do read most mails decently nowadays but there are still quite a few times where I need to copy the email into for example a new mail box in gmail under Chrome, in order to check some words using rikaikun.

Whatever you choose to do, thank you in advance and I will definitely donate something when done on Thunderbird :)

**Comment by birtles** [comment] 2020-12-08 01:04
Thank you @rzvnbr and @SamXtusJapan! Yes, I understand how helpful this would be for Thunderbird (I switched from Thunderbird to Gmail simply because I relied heavily on Rikaichamp). Please don't hesitate to keep reminding me about this if it seems to be taking too long.

**Comment by jmbattle0** [comment] 2020-12-08 07:33
@birtles thank you for continuing to work on this.

For what it's worth, I'm still using Thunderbird 52.9.1 on my work PC in order to continue to use Rikaichan.

**Comment by birtles** [comment] 2021-06-05 03:10
Thanks everyone for your patience here. It looks like the format of Thunderbird extensions has changed as of Thunderbird 78 to MailExtensions. With that in mind I've updated the title of this issue to be more generic.

From what I can tell, using message display scripts and compose scripts we should be able to get Rikaichamp to work when reading and composing messages.

I'm going to try and make time for this in the coming weeks. I really appreciate your patience and continual reminders about this. You folks are really great.

**Comment by Lebon14** [comment] 2021-06-05 03:54
Awesome. Looking forward to it!

**Comment by hakbaratar** [comment] 2022-05-27 00:09
@birtles Thanks a lot for your efforts to improve the reader - it remains valuable every day!!!
And sorry for asking again about the Thunderbird support. I am still using TB52.9. How are the chances for an update of the reader?

**Comment by birtles** [comment] 2022-05-28 06:01
@hakbaratar Thank you very much for your comments!
Thunderbird is next on the list. I'm really grateful for your comment because I haven't heard anyone asking for Thunderbird support recently so I was starting to wonder if it was still needed.

**Comment by hakbaratar** [comment] 2022-05-28 06:30
Oh yes, definitely it is still needed (also considering that TB made much progress). I guess everybody is just waiting and does not want to push you too hard.

**Comment by SamXtusJapan** [comment] 2022-05-28 06:36
Same opinion here, I'm still using Thunderbird and it is still needed for me too.

**Comment by brainexcerpts** [comment] 2022-05-28 06:50
I've been watching this for god knows how long XD I had to resort to see my email threw webbrowsing ever since the plugin become obsolete. From experience people willing to notify represent at most 2-3% of people that would actually be happy to have feature X or bug Y fix but never bothered asking. Github is not even that visible to normal none IT oriented people, so yeah if you ever get time my guess lots of people will be extremly pleased :D

**Comment by birtles** [comment] 2022-05-28 07:01
Great, thanks everyone. That's really helpful feedback.

**Comment by birtles** [comment] 2022-05-30 06:28
I made a little progress on this today. So far it's looking do-able.

![image](https://user-images.githubusercontent.com/1232595/170930271-6e388b47-387e-40cd-b1c0-4f5578e3710b.png)

**Comment by birtles** [comment] 2022-05-30 06:47
It seems to work in compose window in both HTML and plain text mode too (note to self: hold <kbd>Shift</kbd> while clicking the "Write" button to switch modes).

A couple of quick notes for myself for things left to do:

- [ ] We probably don't need to show the label next to the icon in the main window
- [ ] It's possible the icon in the main window doesn't update unless the user clicks it?
- [ ] There's no icon (browser action) in compose window. Can we add one?
- [ ] We need to add CI support for producing the Thunderbird artifact
- [ ] The default shortcut for disabling the addon (<kbd>Alt</kbd> + <kbd>R</kbd>) doesn't seem to work
- [ ] Check if we actually need all the tab switching code
- [ ] Get the manifest to use a separate minimum version for Thunderbird (likely v91?) to Firefox

**Comment by hakbaratar** [comment] 2022-05-30 11:48
@birtles  Thanks for turning to this so quickly. It looks indeed very promising!
Sorry, I do not know about the technical details. However, the label isn't indeed really needed.

**Comment by FmT0** [comment] 2022-05-30 21:35
This is a REALLY GOOD NEWS !!! Only feature I would like is just to be able a quick on/off with right click in the message menu.

**Comment by Lebon14** [comment] 2022-05-30 23:31
Amazing news!

**Comment by birtles** [comment] 2022-06-02 09:27
Thanks for the encouragement everyone. I _think_ I've fixed the most serious issues now. I just need to fix toggling from the context menu: the menu item doesn't show up at all.

**Comment by birtles** [comment] 2022-06-06 06:03
With any luck, this might now be available to install here for Thunderbird 91+: https://addons.thunderbird.net/thunderbird/addon/10ten-ja-reader/

Can anyone confirm that it works?

**Comment by SamXtusJapan** [comment] 2022-06-06 06:15
Working perfectly for me, well done, thank you very much ! I saw there is no button but since we can enable/disable it using alt+shif+r or by right clicking for context menu to enable it, it seems perfectly fine.

**Comment by birtles** [comment] 2022-06-06 06:16
Thank you for confirming!
There should be a button up in the top-right of the main window and compose window. Is it missing?

**Comment by SamXtusJapan** [comment] 2022-06-06 06:29
> Thank you for confirming! There should be a button up in the top-right of the main window and compose window. Is it missing?

I confirm it's missing. I have just updated to Thunderbird 32b 91.10.0, I first tried with v. 91.9. The only thing that's showing is the pop-up bubble-like button if I enable it in the settings.

**Comment by SamXtusJapan** [comment] 2022-06-06 06:45
Oh, actually the toolbar button does show, but I need to manually add it to each tool bar, that is right click in main window toolbar > personalize > drag and drop the button, same for compose window. From there on it seems to stay there and work correctly so it's ok but would be nice to have it added to the toolbar by default after install.

**Comment by SamXtusJapan** [comment] 2022-06-06 06:52
Also :
 - Also, after forcing the bubble button on, it does display but doesn't seem to work for me
 - I can confirm other language definition do show correctly (I tried French)

**Comment by SamXtusJapan** [comment] 2022-06-06 06:59
Also inside the pop up window, I can't go to the 人名 or 漢字 tab if I haven't left clicked somewhere on the pane where the text is before poping up the translation. At first I thought the tab switching wasn't working at all.

I guess it's not that odd to need to select the pane, but it's not obvious neither (since the pop up does show without selecting it), so it would be nice to either :
- remove the need to select the text pane before switching tabs in the pop-up
- if not possible, add the need to select the text pane before enabling the auto pop-up of the translation when hovering the mouse on japanese text : a first time user noticing the pop-up doesn't show would probably try to click on the pane imo.
- if not possible add some tutorial or something to explain that we need to select the text pane to be able to switch tabs, it took me 5 min to understand myself how I was able to make it work once.

**Comment by SamXtusJapan** [comment] 2022-06-06 07:03
That's it for my comments, also where should I go for a donation ? :)

**Comment by birtles** [comment] 2022-06-06 07:41
Thanks for all that!

I'm not sure what's happening with regards to the toolbar button not showing. It showed by default for me but perhaps that's because I freshly installed Thunderbird. Maybe if you've customized the toolbars at all it won't show?

Regarding needing to focus the window in order to switch it -- I think that's likely a limitation of Thunderbird / Mail extensions due to the keyboard events firing on a different window to the mouse events. The same problem happens in Firefox etc. but it's just that you much rarely use multiple windows simultaneously there. Maybe there's a way to work around it, but only if the focussed window happens to also have the content script running in it. It's probably worth filing as a separate issue to investigate. (Longer-term, we want to make that more window interactive using the mouse so that would help a bit too.)

I'm going to close this issue for now, so we can file separate issues for follow-up work.

Thanks for the offer to donate too. I really appreciate it. We're working on something you can contribute but it's still quite a long way off. For now, we really appreciate follows on Twitter, reviews on add-ons pages, spreading the word in forums, and, of course, bug reports!

**Closed** 2022-06-06 07:41 UTC

**Comment by SamXtusJapan** [comment] 2022-06-06 08:07
Regarding the toolbar, it could very well be something related to what I modified on my Thunderbird. I don't remember modifying the toolbars specifically, but my Thunderbird isn't a fresh install at all. I work on Windows 10 and several years ago I actually even replaced the user profile folder (C:\Users\<UserName>\AppData\Roaming\Thunderbird\Profiles) to get my mail archives back from my older PC.

Regarding the need to focus the window to switch 10-ten tabs, it's actually noticeable because you need to reselect it everytime you switch from one mail to another. I will probably not switch those tabs very often, but in my normal every day use I definitely don't click on the contents of each email I receive, I just select them from the email list and read them one by one. If needed, I do hover the mouse on the contents with 10-ten to get the translation but I don't usually click on them. When you know it it's very easy to workaround but it's not exactly natural so some people will probably miss it (or maybe forget it after several months not using it for instance). Now if there is a long term plan around that I don't mind keeping it like this until then, really not a big deal :)

Regarding the reviews on add-on page, I already added mine (samurai80 there). Keep up the great work !

**Comment by birtles** [comment] 2022-06-06 08:34
All good points. It really would be good to fix that focus issue but it's probably a bit of work, unfortunately.
Thanks for the review!
