### ISSUE TITLE
Does not appear in Safari extensions list

### ISSUE THREAD

**Issue by elmimmo** [birchill/10ten-ja-reader#974] opened 2022-07-26 03:49 UTC
10ten Japanese Reader installed from the Mac App Store does not appear in Safari’s toolbar nor in menu Safari ▸ Preferences… ▸ Extensions. Other extensions do show in that screen.

Launching the app 10ten Japanese Reader brings up a window with the message “You can turn on 10ten Japanese Reader’s extension in Safari Extensions preferences” and a button that reads "Quit and Open Safari Extensions Preferences…". Pressing the button does neither.

Seen with:
* 10ten Japanese Reader Version 1.10.6 (43)
* Safari Version 15.5 (17613.2.7.1.8)
* macOS Monterrey Version 12.4 (21F79)

**Comment by birtles** [comment] 2022-07-26 03:57
Oh, that's a worry. It seems to work for me here although I'm on Monterey version 12.5 and Safari 15.6.

Forgive me if you've already tried this, but I wonder if you can quit and restart Safari and see if it is available?

**Comment by elmimmo** [comment] 2022-07-30 14:45
I did try restarting and still did not work. It did work after upgrading to macOS 12.5 (21G72) and Safari 15.6 (17613.3.9.1.5).

**Comment by birtles** [comment] 2022-08-01 00:30
Thank you for following up on this!

I hope other people on macOS 12.4 / Safari 15.5 are not experience the same problem.

**Comment by elmimmo** [comment] 2022-10-21 22:55
It is happening to me again, exactly same behavior, now with:

- 10ten Japanese Reader Version 1.12.5 (50)
- Safari Version 16.0 (17614.1.25.9.10, 17614)
- macOS Monterrey Version 12.6 (21G115)

**Comment by birtles** [comment] 2022-10-22 01:19
@elmimmo Do any of the suggestions in https://github.com/birchill/10ten-ja-reader/issues/1002#issuecomment-1280459334 help?

**Comment by elmimmo** [comment] 2022-10-23 22:35
I ran the suggested command to reset the Launch Services database and 10ten did appear back in the Safari extensions list. It might have been the command, or the fact that just before running it I had installed yet another extension (yes, my bad for not trying one thing at a time).

**Comment by birtles** [comment] 2022-10-24 01:07
That's great to hear that it's working now. I'll go ahead and close this for now but please re-open it if the problem is not resolved.

**Closed by birtles** 2022-10-24 01:07 UTC
