### ISSUE TITLE
No option to ignore numbers

### ISSUE THREAD

**Issue by Adelysk** [birchill/10ten-ja-reader#751] opened 2021-09-09 14:07 UTC
Reader recognizes numbers like "21" everywhere, even in url. It is very annoying, and there is no option to deactivate that.

**Comment by birtles** [comment] 2021-09-09 22:58
Hi @Adelysk !

Thank you for filing this issue. Sorry about the annoyance!

This issue should be fixed from version 1.3.2 onwards. I think you might have been unlucky to have updated during the short time window when 1.3.1 was available.

Can you try updating to see if the issue is fixed? The current version is 1.3.3.

**Comment by birtles** [comment] 2021-09-10 09:01
I haven't heard back about this so I'm assuming it's fixed. Closing for now but please let me know if you still see this.

**Closed by birtles** 2021-09-10 09:01 UTC

**Comment by Adelysk** [comment] 2021-09-10 09:16
I was sleeping sorry. Yes it got fixed with the update this morning. Thank you very much and sorry for the unnecessary report. ^^'

**Comment by birtles** [comment] 2021-09-10 09:16
Thank you! Sorry for the annoying behavior!
